# Generated by Django 2.1.5 on 2023-08-02 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_auto_20220811_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientsymptomsanalysis',
            name='createdon',
            field=models.DateTimeField(auto_now_add=True, max_length=50),
        ),
    ]
